### PR TITLE
Add a Makefile for convienience

### PR DESCRIPTION
**Pull request by ghost**
### Add Makefile
* Easier to interact with project
### Modify Readme
* Include instructions for using Makefile
* Edit list of dependecies
### Add .gitignore
* Force git to ignore virtual environment and unwanted python files

### CODE REVIEW

**Comment by nhyldmar** [comment]
Is `python3-numpy libsdl2-dev libffi-dev libomp5` on line 55 of the makefile needed?

**Comment by ghost** [comment]
That is not needed, I will make changes.

**Comment by ghost** [comment]
> Is `python3-numpy libsdl2-dev libffi-dev libomp5` on line 55 of the makefile needed?

Removed.

**Comment by UtilityHotbar** [comment]
Hey, I don't think this project requires a makefile atm (it's literally `python3 main.py` to run), so I'll put this on hold for now. Thanks for the help anyways!

**Pull request closed without merging**
